### ISSUE TITLE
Learning Status of Parsed Words Unable to be Changed

### ISSUE THREAD

**Issue by realestskillz** [migaku-official/migaku-browser-extension-issue-tracker#18]
**Describe the bug**
After parsing a webpage in Chrome or a Netflix show, hovering over or clicking an underlined word yields no result.

**To Reproduce**
1. Click "Parse" button in Migaku toolbar
2. Hover over or click on word to no effect

**Expected behavior**
An option similar to this (from older version):
![image](https://user-images.githubusercontent.com/97123114/148107137-7b5f4002-b6e2-4f6a-821f-18542a62dbcd.png)

**Screenshots**

**Desktop (please complete the following information):**
 - OS: mac OS
 - Version 0.9.1.1
 
**Additional context**

**Comment by KieranBrannigan** [comment]
Thanks for the bug report 😊

I just want to make sure, are you holding `Shift` while hovering the word?

**Comment by KieranBrannigan** [comment]
Thanks for the bug report 😊

I just want to make sure, are you holding `Shift` while hovering the word?

**Comment by realestskillz** [comment]
The parsing stuff looks fixed/much better in 0.9.2.1 :)  Thanks!
