### ISSUE TITLE
Server error when attempting to download dictionary 

### ISSUE THREAD

**Issue by Lucyhenley** [migaku-official/migaku-browser-extension-issue-tracker#21]
**Describe the bug**
Server error when attempting to download dictionary in the installation wizard on the browser extension. The same issue also occurs with frequency lists.

**To Reproduce**
Try and download a dictionary using the installation wizard, using the default migaku server.

**Screenshots**
<img width="959" alt="screenshot" src="https://user-images.githubusercontent.com/46442845/152641785-8a74672e-56c4-4bec-b02c-62758628da21.PNG">

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version 0.8.2.2

**Additional context**
No issues when downloading the same dictionary from the same server on the anki extension

**Comment by KieranBrannigan** [comment]
Hello, this error might happen occasionally due to network problems. However if you consistently get this error please let us know. 

I am going to close the issue for now, but if you still consistently get this error on the newest version of the extension please let us know :)
