### ISSUE TITLE
Incorrect "watch a video" hyperlink URL

### ISSUE THREAD

**Issue by saxoncameron** [migaku-official/migaku-browser-extension-issue-tracker#22]
## Description

The "Watch a video" hyperlink in the "What is the Migaku Browser Extension" CTA of the Migaku Settings dashboard, links to:
https://en.wikipedia.org/wiki/Standard_Chinese_phonology#Tones

## Expected behaviour

It links to the described video, or otherwise has a note that the video is coming soon etc.

## Screenshot

![image](https://user-images.githubusercontent.com/3240185/153533294-50dc9b38-5886-44f2-bc70-64b141fc4553.png)

**Comment by LucasMIA** [comment]
These links will all be updated before beta so I will close this issue until then. Please let us know if you find any incorrect links in the beta release though.
