### ISSUE TITLE
Searching Dictionary when window is closed, doesn't search term

### ISSUE THREAD

**Issue by saxoncameron** [migaku-official/migaku-browser-extension-issue-tracker#23]
**Describe the bug**
When Migaku Dictionary window is closed, and I search a word (using the global hotkey), the dictionary opens but does not search the word. Searching the word only works if the window is already open. In other words, if the Dictionary window is closed, you have to search the same term twice - once to open the window, and a second time to search the term.

**To Reproduce**
1. Have any Migaku Dictionary windows closed
2. Search any highlighted term using the global Migaku Dictionary hotkey
3. Notice the window opens, but the highlighted term isn't searched
4. Search the same highlighted term again using the same hotkey
5. Now that the dictionary window is open, the term is searched correctly in the dictionary window

**Expected behavior**
Searching a term while the dictionary window is closed, open the dictionary and searches the term.

**Screenshots**
N/A

**Desktop (please complete the following information):**
 - OS: macOS Monterey 12.1; MacBook Pro 16" 2019
 - Browser extension v0.9.3.2
 - Anki addon 0.1.0-alpha.12

**Comment by LucasMIA** [comment]
This seems to work for me, does it never work for you or is it an intermittent issue?

**Comment by KieranBrannigan** [comment]
I also cannot reproduce this error. :/

Going to close this due to inactivity, but if you do find this bug is reproduceable please comment again and we will reopen this issue 👍

**Comment by saxoncameron** [comment]
Sorry for the late reply.

Yes it still happens for me, and reliably so. **Interestingly, it only happens when I used the global search hotkey**. If I highlight a word, press control, then press the search icon, the dictionary opens and searches as intended.

Let me know if there's anything else I can do to help troubleshoot or replicate this issue.

**Comment by saxoncameron** [comment]
Still occurring for me in v0.9.9.2 and anki addon alpha 17

**Comment by saxoncameron** [comment]
FYI @KieranMigaku this issue persisted until just recently, where it is no longer a problem. This seems to coincide with the latest Anki Addon release `0.2.2`
