### ISSUE TITLE
Card creation button inaccessible on youtube when native subtitles are disabled

### ISSUE THREAD

**Issue by lkls89** [migaku-official/migaku-browser-extension-issue-tracker#25]
**Describe the bug**
When there is no native subtitle track selected, the button for sending a line from the youtube player to the card creator is too low and  and therefore (partially) covered by the youtube UI.

**To Reproduce**
1. Go to Youtube
2. Hover over the subtitle area (subtitle must be <=2 lines long) to bring up the look up and card creation buttons
3. See error

**Expected behavior**
Both buttons are fully accessible.

**Screenshots**
![image](https://user-images.githubusercontent.com/95383902/153635774-0f489f33-b5d9-4ed4-a59e-61a5c5540bd8.png)

**Desktop (please complete the following information):**
 - OS: Win11
 - Version 0.9.3.2
 - Naver Whale Browser

**Additional context**
Font size 25

**Comment by LucasMIA** [comment]
Fixed
