### ISSUE TITLE
Browser Extension fails to fetch Tatoeba, Forvo and Google Images

### ISSUE THREAD

**Issue by ghost** [migaku-official/migaku-browser-extension-issue-tracker#46]
Describe the bug

Recently the chrome extension has not been able to fetch any Tatoeba, Forvo or google images examples for words.

To Reproduce

Opening The Migaku Dictionary from the extension
Type any vocabulary into the search bar so that there is at least one dictionary definition loaded

![image](https://user-images.githubusercontent.com/2927772/198864888-d1d17881-dcd0-4ba2-ad15-ff099319a4f6.png)

Desktop:

OS: Windows 10
Chrome Version 106.0.5249.119

Additional context

This was previously working, but has not stopped across all dictionary entries, no example audio sentences or images can be found. Has not been working for approximately 2-3 weeks.

**Comment by rlanday** [comment]
I’m also having this problem. My newly-created flashcards are missing all this stuff. The problem seems to started for me sometime on 2022-10-28 (Taiwan time).

**Comment by rlanday** [comment]
I figured out my problem was that “Add definitions automatically” had somehow become unchecked in the Card Creator. Is this actually a useful setting, or should it always be enabled?

**Comment by ghost** [comment]
> 

Just to check I tried disabling, enabling etc that and add cards automatically, but it still failed to fetch any external sources like audio or images.

**Comment by MinmoTech** [comment]
Very late response, but this issue occurs when you don't allow the extension access to all websites :)
