### ISSUE TITLE
Migaku Chinese Settings Screen Bugged

### ISSUE THREAD

**Issue by Anmyks** [migaku-official/migaku-browser-extension-issue-tracker#7]
**Describe the bug**
The Migaku Chinese settings window doesn't resize the contents when the corner is dragged, so the boxes for choosing tone colors and other settings are impossible to see.

**To Reproduce**
1. Go to Settings Window

**Expected behavior**
Window resizes content frames along with window.

**Screenshots**
![Capture](https://user-images.githubusercontent.com/35441294/144735489-d9012cd5-0753-4d92-8cbe-66f92e751bb2.PNG)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version 1.2.3

**Additional context**
I've tried reinstalling Anki, reinstalling Migaku Chinese, and playing around with my settings to no avail.

**Comment by KieranBrannigan** [comment]
Sorry this bug went unnoticed for so long, however I am going to close this issue because it is not related to the Migaku browser extension. I would suggest updating to the new Migaku Anki Addon which makes a lot of the processes between Anki and the Migaku browser extension much simpler.
