### ISSUE TITLE
Korean Syncing Nonfunctional

### ISSUE THREAD

**Issue by carlos-kelley** [migaku-official/migaku-browser-extension-issue-tracker#8]
**Describe the bug**
Korean known words do not sync.

**To Reproduce**
1. Go to 'Learning Status' in Korean
2. Click on 'Sync Word List'
3. Word list is not synced. Repeat step 1 and 2 on different computer and no words are transferred or synced. Completely nonfunctional/

**Expected behavior**
Words are synced.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - All browsers and OS's.

**Additional context**
Syncing tested working on Romance languages, just not Korean.

**Comment by KieranBrannigan** [comment]
Thank you for your bug report.

We will try to get around to working on this as soon as possible after we finish working on some upcoming releases.

I tried a little and I am not able to reproduce this error. 
Can you make sure you have korean selected from the dropdown in the top right of the settings page. 
Also just to make sure: 
- After marking some words as known when you click sync you should click "Upload to Migaku Cloud". Now they are synced to the cloud so they are available on different devices.
- If you want to get your known words on a fresh install you should click sync, then click "Download From Migaku Cloud"

**Comment by MinmoTech** [comment]
Sorry @KieranMigaku, I fixed this recently.
